source ~/.config/nvim/vim-plug/plugins.vim
source ~/.config/nvim/general/settings.vim
source ~/.config/nvim/general/theme.vim
source ~/.config/nvim/general/mappings.vim
source ~/.config/nvim/config-plug/autopep8.vim
source ~/.config/nvim/config-plug/coq.vim
source ~/.config/nvim/config-plug/devicons.vim
source ~/.config/nvim/config-plug/easy-align.vim
source ~/.config/nvim/config-plug/fzf.vim
source ~/.config/nvim/config-plug/fugitive.vim
source ~/.config/nvim/config-plug/go.vim
source ~/.config/nvim/config-plug/indent-blankline.lua
source ~/.config/nvim/config-plug/lightline.vim
source ~/.config/nvim/config-plug/lspconfig.vim
source ~/.config/nvim/config-plug/mundo.vim
source ~/.config/nvim/config-plug/quickscope.vim
